### ISSUE TITLE
Rolltable suggestions

### ISSUE THREAD

**Issue by ghost** [MajorVictory/Pokemon5e-items#1]
Encounter tables based on possibly region and habitat. [Here is a great habitat resource](https://www.theworldofpokemon.com/habitats1.html?utm_source=share&utm_medium=ios_app) that I use, might be interesting.

On page 17 of the Pokemon 5e PHB there are also some nice weather tables that could be converted.

**Comment by MajorVictory** [comment]
I've added the weather tables. The encounter tables might be a 'later' thing as there's quite a few of those and it would take some time to set them up the way I'd like.
As it is, tables referencing items or creatures should have a draggable token from the chatbox when used.

**Comment by MajorVictory** [comment]
Version 1.1.0 now has a bunch of encounter tables by habitat.
